[package]
name = "seven"
version = "0.1.0"
authors = ["Andreas Haug <andrea2@uio.no>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
itertools = "0.10.0"